services:
    database:
        image: 'postgres:15.4'
        container_name: database
        hostname: database
        environment:
            POSTGRES_DB: ${DATABASE_DB}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${DATABASE_EXPOSE_PORT}:5432
        volumes:
            - ${DATABASE_INIT}:/docker-entrypoint-initdb.d
            - ${DATABASE_STORE}:/var/lib/postgresql/data
        #      - ${DATABASE_SSL}:/etc/ssl/certs
        restart: always
    #    command: >
    #      -c ssl=on
    #      -c ssl_cert_file=/etc/ssl/certs/localhost.crt
    #      -c ssl_key_file=/etc/ssl/certs/localhost.key
