server:
    port: 8080

logging:
    file:
        path: /var/log
    level:
        org:
            springframework:
                security: DEBUG


spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST_PORT}/${DATABASE_DB}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    docker:
        compose:
            enabled: true
            lifecycle-management: start_only

springdoc:
    swagger-ui:
        path: /swagger-ui.html

cors:
    allowedOrigins: ${ALLOWED_ORIGINS:http://localhost,https://localhost}
    allowedMethods: ${ALLOWED_METHODS:*}
    allowedHeaders: ${ALLOWED_HEADERS:*}

jwt:
    secret: ${JWT_SECRET:secret}
    expiration-min: ${JWT_EXPIRATION_MIN:100}
    cookie-name: ${JWT_COOKIE_NAME:jwt}