CREATE SCHEMA IF NOT EXISTS db;

create table db."user"
(
    id          bigint generated by default as identity
        constraint user_pk
            primary key,
    username    varchar              not null
        constraint username_uniq
            unique,
    create_time timestamp with time zone default now() not null,
    password    varchar              not null,
    enable      boolean default true not null
);

comment on table db."user" is 'user information';


create table db.permission
(
    id   bigint generated by default as identity
        constraint permission_pk
            primary key,
    code varchar not null,
    name varchar not null
);

comment on table db.permission is 'user permission';

create table db.role
(
    id   bigint generated by default as identity
        constraint role_pk
            primary key,
    code varchar not null,
    name varchar not null
);

comment on table db.role is 'user role';

create table db.role_permission_map
(
    id            bigint generated by default as identity
        primary key,
    role_id       bigint not null,
    permission_id bigint not null
);

comment on table db.role_permission_map is 'user role_permission_map';

create table db.user_role_map
(
    id      bigint generated by default as identity
        primary key,
    user_id bigint not null,
    role_id bigint not null
);

comment on table db.user_role_map is 'user user_role_map';
